package com.example.burnestimation.viewmodels

import android.util.Log
import androidx.lifecycle.*
import com.example.burnestimation.datamodel.Patient
import com.example.burnestimation.datamodel.PatientRepository
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch
import java.lang.IllegalArgumentException

class PatientViewModel(private val repository: PatientRepository) : ViewModel() {

    // Using Live Data and caching what allWords returns has several benefits
    // - We can put as observer on the data (instead of polling for changes)
    //   and only update the UI when the data actually changes.
    // - Repository is completely separated from the UI through the ViewModel.
    val allPatients: LiveData<List<Patient>> = repository.allPatients.asLiveData()

    /**
     * Launching a new coroutine to insert the data in a non-blocking way
     *
     * return autogenerated key
     */
    fun insert(patient: Patient): LiveData<Long> {
        val result = MutableLiveData<Long>()
        viewModelScope.launch {
            Log.d("PatientViewModel", "insert patient")
            val returned = repository.insert(patient)
            result.postValue(returned)
        }
        return result
    }

    fun getPatient(patientId: Int): LiveData<Patient> = repository.getPatient(patientId).asLiveData()

}

class PatientViewModelFactory(private val repository: PatientRepository) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        if (modelClass.isAssignableFrom(PatientViewModel::class.java)) {
            Log.d("PatientViewModel", "init")
            @Suppress("UNCHECKED_CAST")
            return PatientViewModel(repository) as T
        }
        throw IllegalArgumentException("Unknown ViewModel class")
    }
}